eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   #register in the centralised service registry i.e eurekha
    register-with-eureka: true   #It allows registering the services in the eurekha services
    fetch-registry: true    #It allows micrservices to cmmunicate with each other
  instance:
    prefer-ip-address: true  #Service register with its ipaddress instead of the hostname