server:
  port: 8084

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-repo/config-repo  # Replace with your actual repo
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
